---

name: seismic
channels:
  - bioconda
  - conda-forge
dependencies:
  - python >=3.10
  - bowtie2 >=2.5.4
  - fastp >=0.23.0
  - rnastructure >=6.4
  - samtools >=1.20
  - brotli-python >=1.0
  - python-kaleido >=0.2.1